version: '3.8'  # Actualiza a una versión más reciente

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:9000"
    volumes:
      - .:/var/www
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
